### ISSUE TITLE
Github App required?

### ISSUE THREAD

**Issue by tomekc** [ataylorme/eslint-annotate-action#11]
Hi, I'm getting error "You must authenticate with GitHub app". 
I've used personal access token; does it mean I need to create GitHub app to use your action?

**Comment by ataylorme** [comment]
Hi @tomekc,
You do **not** need a personal access token or a GitHub App.

GitHub Actions provides a pre-authenticated token for the repo the workflow is run on. It is stored as an [encrypted secret](https://docs.github.com/en/actions/reference/encrypted-secrets) named [`GITHUB_TOKEN`](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret).

If you look at [the usage example in the `README`](https://github.com/ataylorme/eslint-annotate-action#usage-example) it shows how to use the `GITHUB_TOKEN` secret with this Action.

```yaml
- name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.1.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"
```

I hope that helps!
