### ISSUE TITLE
Feature Request: Handling warnings: --max-warnings Int

### ISSUE THREAD

**Issue by mark-lison** [ataylorme/eslint-annotate-action#19]
This action is working great
When we use eslint we set the flag --max-warnings=0
It would be really useful if the same setting could be added to this action, so that when the maximum number of warnings has been exceeded the GitHub Action reports failure.

**Comment by ataylorme** [comment]
@mark-lison would an input for the GitHub Action `fail-on-warning` work? I could see this being a boolean that defaults to `false` but you could pass in `true` when running the Action like this:

```
- name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.1.3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"
          fail-on-warning: true
```

**Comment by mark-lison** [comment]
Yes that would work for us.

**Comment by ataylorme** [comment]
@mark-lison please test this on [the `1.2.0-beta1` tag](https://github.com/ataylorme/eslint-annotate-action/tree/1.2.0-beta1)

You can call the Action and specify a version like this:

```
- name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.2.0-beta1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"
          fail-on-warning: true
```

If it tests well for you I can merge #20 and do a full release for `1.2.0`
