### ISSUE TITLE
Support read-only tokens

### ISSUE THREAD

**Issue by JosephDuffy** [ataylorme/eslint-annotate-action#28]
When using a read-only token (e.g. in a PR from a fork) the action fails with the error `Resource not accessible by integration` (this issue seems to be [affecting this repo](https://github.com/ataylorme/eslint-annotate-action/runs/2795421128?check_suite_focus=true))

I'm thinking it might be possible to emit the warnings and errors via workflow commands. For example [`echo "::warning file=app.js,line=1,col=5::Missing semicolon"`](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message).

**Comment by zomars** [comment]
I'm having this exact issue

**Comment by ataylorme** [comment]
This Action create a new GitHub status check which requires the following permission. Without that permission the purpose of the Action, to annotate the PR, is lost.
```
github-token:
  action-input:
    input: repo-token
  permissions:
    checks: write
    checks-reason: to create checks
    pull-requests: read
    pull-requests-reason: to get changed PR files
```

If you need to show lining errors in your GitHub Action test you can run ESLint directly without using this action.
