### ISSUE TITLE
Annotations show up as part of a different workflow

### ISSUE THREAD

**Issue by oxc** [ataylorme/eslint-annotate-action#35]
I have multiple workflows that get triggered on pull_request. One of them is called "Run tests for pull request" and has a job called "Run linter" that runs the `eslint-annotate-action`.

However, the annotations often show up as child of a completely unrelated workflow. It seems undeterministic under which workflow it shows up.

In the following example, the annotation results wrongly show up as part of the "Code coverage" workflow:
![image](https://user-images.githubusercontent.com/1388972/148072259-a2d90776-1cb1-41e2-861f-d49640211a1d.png)

Here is an excerpt from the workflow that runs the action:

```yaml
name: Run tests for pull request

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm run install:all

      - name: Generate lint report
        run: npm run lint:report
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          report-json: eslint_combined_report.json
```
