### ISSUE TITLE
Documentation improvement: remove or explain point of actions/upload-artifact in the usage example

### ISSUE THREAD

**Issue by atsu85** [ataylorme/eslint-annotate-action#51]
Currently [usage example](https://github.com/ataylorme/eslint-annotate-action/tree/2450c2aa1460446829f338b254cf49247cb45449#usage-example) contains:
```yaml
      - name: Upload ESLint report
        uses: actions/upload-artifact@v2
        with:
          name: eslint_report.json
          path: eslint_report.json
```

There is no explanation why or in which cases it could be useful. I got it working without it. 

# Potential explanation???

I'm guessing that if for some weird reason you'd like to run linting code and `ataylorme/eslint-annotate-action` in different jobs, then you could use `actions/upload-artifact` to save the report json file, so it could be loaded by next job that uses `ataylorme/eslint-annotate-action`, but currently i don't understand why would someone do that either.

# Suggestion
Just remove the step related to `actions/upload-artifact` action from the usage example or add comment why that could be useful
