### ISSUE TITLE
Node 12 actions are deprecated

### ISSUE THREAD

**Issue by mrmeyers99** [ataylorme/eslint-annotate-action#60]
I get the following warning when using this action:

```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: ataylorme/eslint-annotate-action@1.2.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

This action needs to be upgraded to Node 16 to get rid of that warning.

**Comment by ataylorme** [comment]
@mrmeyers99 which version of the action are you using? `v2` does use Node 16 ([see here](https://github.com/ataylorme/eslint-annotate-action/blob/v2/action.yml#L32))

It can be used like this:

```
- name: Annotate Code Linting Results
  uses: ataylorme/eslint-annotate-action@v2
  with:
    repo-token: "${{ secrets.GITHUB_TOKEN }}"
    report-json: "eslint_report.json"
```
