### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by thefrosty** [ataylorme/eslint-annotate-action#82]
Using:
```yml
on:
  pull_request:

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v3
        if: ${{ always() && steps.eslint.outcome == 'failure' }}
        with:
          report-json: 'standard_report.json'
          markdown-report-on-step-summary: ${{ true }}
```

```text
Starting analysis of the ESLint report standard_report.json. Standby...
/home/runner/work/_actions/ataylorme/eslint-annotate-action/v3/dist/index.js:56451
        file.filePath = file.filePath.replace(GITHUB_WORKSPACE + '/', '');
                                      ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at /home/runner/work/_actions/ataylorme/eslint-annotate-action/v3/dist/index.js:56451:39
    at Array.filter (<anonymous>)
    at getPullRequestChangedAnalyzedReport (/home/runner/work/_actions/ataylorme/eslint-annotate-action/v3/dist/index.js:56450:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (/home/runner/work/_actions/ataylorme/eslint-annotate-action/v3/dist/index.js:56561:11)
```

**Comment by ataylorme** [comment]
Thanks for tracking this down @thefrosty! This is fixed in [v4.0.0-beta.1](https://github.com/ataylorme/eslint-annotate-action/releases/tag/v4.0.0-beta.1) — `GITHUB_WORKSPACE` is now safely defaulted to an empty string when unset, and the path-stripping logic guards with a `startsWith` check before slicing.

Please test the beta when you get a chance:
```yaml
- uses: ataylorme/eslint-annotate-action@v4.0.0-beta.1
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    report-json: eslint_report.json
```
