### ISSUE TITLE
Double comments on annotations

### ISSUE THREAD

**Issue by rubengmurray** [ataylorme/eslint-annotate-action#83]
I'm seeing double annotations in some cases.

The example YAML names the job as `node_test` (https://github.com/ataylorme/eslint-annotate-action#usage-example) which is the name on one of the comments, and then we have the `ESLint Report Analysis` genuine name on others.

Here's a screenshot:

<img width="1343" alt="Screenshot 2024-07-19 at 15 16 31" src="https://github.com/user-attachments/assets/0ba75f19-c80e-4860-b73d-b17010797ef2">

And another:

<img width="1348" alt="Screenshot 2024-07-19 at 15 16 45" src="https://github.com/user-attachments/assets/fa3c500a-60c3-4f1a-bf8b-73d52bab6b2d">

**Comment by ataylorme** [comment]
Thanks for the report @rubengmurray! The v4 rewrite includes a new `post-comment: true` input that handles this properly — it upserts a single PR comment using a hidden HTML marker, so you'll never get duplicate comments even if the workflow runs multiple times.

Please give [v4.0.0-beta.1](https://github.com/ataylorme/eslint-annotate-action/releases/tag/v4.0.0-beta.1) a try:
```yaml
- uses: ataylorme/eslint-annotate-action@v4.0.0-beta.1
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    report-json: eslint_report.json
    post-comment: true
```
